
// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// A default [FirebaseOptions] instance for each supported platform has been
/// generated from the Firebase apps you have configured in your Firebase project.
///
/// You can use this file as a reference to help you configure your own Firebase
/// apps.
///
/// PLEASE REPLACE THE VALUES IN THIS FILE WITH YOUR OWN FIREBASE CONFIGURATION.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          '''DefaultFirebaseOptions have not been configured for android - 
          you can reconfigure this by running the FlutterFire CLI again.''',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          '''DefaultFirebaseOptions have not been configured for ios - 
          you can reconfigure this by running the FlutterFire CLI again.''',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          '''DefaultFirebaseOptions have not been configured for windows - 
          you can reconfigure this by running the FlutterFire CLI again.''',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          '''DefaultFirebaseOptions have not been configured for linux - 
          you can reconfigure this by running the FlutterFire CLI again.''',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBN3KCBGbWYd5gpygwQTAEIX8wj4x-bX4E',
    appId: '1:223418724251:web:65c78a677e32d02c537b3e',
    messagingSenderId: '223418724251',
    projectId: 'ttco-ce6db',
    authDomain: 'ttco-ce6db.firebaseapp.com',
    storageBucket: 'ttco-ce6db.appspot.com',
  );


  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBN3KCBGbWYd5gpygwQTAEIX8wj4x-bX4E',
    appId: '1:223418724251:web:65c78a677e32d02c537b3e',
    messagingSenderId: '223418724251',
    projectId: 'ttco-ce6db',
    storageBucket: 'ttco-ce6db.appspot.com',
    iosBundleId: 'com.example.myapp',
  );
}
